services:
  app:
    build: .
    container_name: akurat_app_dev    # Nama berbeda
    volumes:
      - .:/var/www

  db:
    image: postgres:15
    container_name: akurat_db_dev     # Nama berbeda
    environment:
      POSTGRES_DB: db_akurat_dev      # Database berbeda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dinkesmanado2026

  nginx:
    image: nginx:alpine
    container_name: akurat_nginx_dev  # Nama berbeda
    ports:
      - "8080:80"                     # Port berbeda!
    volumes:
      - .:/var/www
      - ./docker-conf/nginx.conf:/etc/nginx/conf.d/default.conf
